<<<<<<< HEAD
# Generated by Django 4.2.6 on 2024-04-13 16:44
=======
# Generated by Django 4.2.6 on 2024-04-20 13:35
>>>>>>> main

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=30)),
                ('kcal', models.IntegerField()),
=======
                ('name', models.CharField(blank=True, max_length=35, null=True)),
                ('kcal', models.IntegerField(blank=True, null=True)),
>>>>>>> main
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('image_link', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('recipe', models.CharField(max_length=150)),
=======
                ('image_link', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=50)),
                ('recipe', models.CharField(max_length=300)),
>>>>>>> main
                ('ingredients', models.ManyToManyField(to='easybitebackendapp.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True)),
<<<<<<< HEAD
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('mealplan', models.CharField(max_length=100)),
=======
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
>>>>>>> main
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('session', models.CharField(max_length=100)),
=======
                ('token', models.CharField(max_length=45, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybitebackendapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('MON', 'Lunes'), ('TUE', 'Martes'), ('WED', 'Miércoles'), ('THU', 'Jueves'), ('FRI', 'Viernes'), ('SAT', 'Sabado'), ('SUN', 'Domingo')], max_length=3)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybitebackendapp.recipes')),
>>>>>>> main
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybitebackendapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybitebackendapp.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easybitebackendapp.user')),
            ],
        ),
    ]
